# This modifies the namespace applied to the application manifests source in
# our base.
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # metadata is used to match the target to patch
  name: auth-tokenexchange
spec:
  targetNamespace: hoy-iam-dev
