apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # metadata is used to match the target to patch
  name: auth-apikeystore
spec:
  patches:
    - target:
        kind: IngressRoute
        name: auth-apikeystore
      patch: |-
        - op: replace
          path: /spec/routes/0/match
          value: Host(`hoy.polysensus.io`) && PathPrefix(`/dev/auth-apikeystore/`) && Method(`GET`)
        - op: replace
          path: /spec/routes/1/match
          value: Host(`hoy.polysensus.io`) && PathPrefix(`/dev/auth-apikeystore/`) && Method(`POST`, `PUT`, `PATCH`, `DELETE`)
        - op: replace
          path: /spec/tls/secretName
          value: cert-wild-hoy-polysensus-io
    - target:
        kind: Middleware
        name: auth-apikeystore-strip-ingressroute-prefix
      patch: |-
        - op: replace
          path: /spec/stripPrefix/prefixes/0
          value: /dev/auth-apikeystore/

