# A flux/Kustomization that will modify the images stanza in a matching
# k8s/Deployment. Note further that the newTag here is the subject of flux image
# update automation. Flux watches for new images in the container registry
# matching a certain  (sortable) tag pattern and when a new one appears it
# *commits* a change to this repository whic replaces 'main-latest' with the
# appropriate tag.
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # metadata is used to match the target to patch
  name: auth-traefikforward
spec:
  images:
  - name: auth-traefikforward
    newName: eu.gcr.io/hoy-dev-1/auth-traefikforward
    newTag: main-6 # {"$imagepolicy": "hoy-iam-dev:auth-traefikforward-main:tag"}
