apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # metadata is used to match the target to patch
  name: auth-apikeystore
spec:
  images:
  - name: auth-apikeystore
    newName: eu.gcr.io/hoy-dev-1/auth-apikeystore
    newTag: main-20 # {"$imagepolicy": "hoy-dev-iam:auth-apikeystore-main:tag"}
