resources:
  - ./secret-auth-tokenexchange-clientssealed.yaml
  # signging key is a 
  - ./secret-auth-tokenexchange-provider-signing-keysealed.yaml

generatorOptions:
  disableNameSuffixHash: true
patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: auth-tokenexchange
    patch: |-
      - op: add
        path: /metadata/annotations/reloader.stakater.com~1match
        value: "true"
configMapGenerator:
  - name: auth-tokenexchange
    literals:
      - PROVIDER=https://sts.hoy.polysensus.io
      - SIGNING_SECRET_FILE=/config/provider-signing-key.json
      - CLIENTS_FILE=/config/clients.json
      - PATH_PREFIX=""
      - APIKEYSTORE_ADDRESS=auth-apikeystore.hoy-iam-dev.svc.cluster.local:8401
      - CLIENT_SCOPES=["email", "openid", "rpc://admin_nodeInfo", "rpc://eth_blockNumber", "rpc://eth_*", "rpc://rpc_modules"]
