---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: auth-tokenexchange
spec:
  interval: 2m
  url: https://github.com/polysensus/auth-tokenexchange
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: auth-tokenexchange
spec:
  interval: 2m
  path: ./k8s/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: auth-tokenexchange
  patches:
    - target:
        kind: Deployment
        name: auth-tokenexchange
      patch: |-
        - op: add
          path: /metadata/annotations/reloader.stakater.com~1search
          value: "true"
