---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: auth-apikeystore
spec:
  interval: 2m
  url: https://github.com/polysensus/auth-apikeystore
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: auth-apikeystore
spec:
  interval: 2m
  path: ./k8s/apikeystore
  prune: true
  sourceRef:
    kind: GitRepository
    name: auth-apikeystore
